# Generated by Django 3.2.4 on 2021-07-10 14:40

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_splash_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_tagline',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
