# Generated by Django 3.2.4 on 2021-08-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mediapage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediapage',
            old_name='media',
            new_name='media_items',
        ),
    ]
